services:
    web:
        image: odoo:17.0
        depends_on:
            - db
        ports:
            - '8069:8069'
        volumes:
            - ./addons:/mnt/extra-addons
            - ./config:/etc/odoo
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
